version: '3.3'

services:
  db: # Container MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    env_file:
      - ./config/wordpress.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
    driver: brigde